let expenses = [
	{
		id: 1,
		date: new Date("7/30/2025").toLocaleDateString(),
		description: "Leen - Hair Dresser",
		amount: 10,
		isPaid: false,
	},
	{
		id: 2,
		date: new Date("7/31/2025").toLocaleDateString(),
		description: "Leen - weekly salary",
		amount: 10,
		isPaid: false,
	},
	{
		id: 3,
		date: new Date("8/2/2025").toLocaleDateString(),
		description: "Dina - day out with Judy",
		amount: 20,
		isPaid: false,
	},
	{
		id: 4,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Dina - monthly expenses salary",
		amount: 70,
		isPaid: false,
	},
	{
		id: 5,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen - 9th grade - tuitions",
		amount: 2112.5,
		isPaid: false,
	},
	{
		id: 6,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen - 9th grade - Books",
		amount: 355,
		isPaid: false,
	},
	{
		id: 7,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Dina - 2nd year 1st semester tuitions + bus",
		amount: 1666,
		isPaid: false,
	},
	{
		id: 8,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Tareq - Home maintenance: Washing Machine",
		amount: 15,
		isPaid: false,
	},
	{
		id: 9,
		date: new Date("8/6/2025").toLocaleDateString(),
		description: "Dina - Amazon birthday gifts",
		amount: 54,
		isPaid: false,
	},
	{
		id: 10,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen - phone monthly recharge",
		amount: 15,
		isPaid: false,
	},
	{
		id: 11,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Leen - Haya Dinner - Better Burger",
		amount: 10.55,
		isPaid: false,
	},
	{
		id: 12,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Dina - Click transfer - Dina's monthly salary",
		amount: 70,
		isPaid: false,
	},
	{
		id: 13,
		date: new Date("8/6/2025").toLocaleDateString(),
		description: "Tareq - Udemy- 2 projects Core - React",
		amount: 15,
		isPaid: false,
	},
	{
		id: 14,
		date: new Date("7/20/2025").toLocaleDateString(),
		description: "Leen - MUN",
		amount: 55,
		isPaid: false,
	},
	{
		id: 15,
		date: new Date("8/7/2025").toLocaleDateString(),
		description: "Tareq - Fish tank supplies",
		amount: 9,
		isPaid: false,
	},
	{
		id: 16,
		date: new Date("7/15/2025").toLocaleDateString(),
		description: " Noor - Shein",
		amount: 51,
		isPaid: false,
	},
	{
		id: 17,
		date: new Date("7/27/2025").toLocaleDateString(),
		description: "Leen - shopping - Bra + shoes",
		amount: 60,
		isPaid: false,
	},
	{
		id: 18,
		date: new Date("8/7/2025").toLocaleDateString(),
		description: "Noor - GMC fuel - 60",
		amount: 60,
		isPaid: false,
	},
	{
		id: 19,
		date: new Date("8/10/2025").toLocaleDateString(),
		description: "Leen - twin-friends birthday gift",
		amount: 23,
		isPaid: false,
	},
	{
		id: 20,
		date: new Date("8/14/2025").toLocaleDateString(),
		description: "Dina - Leen's school bag + Nadi dinner",
		amount: 40,
		isPaid: false,
	},
	{
		id: 21,
		date: new Date("8/14/2025").toLocaleDateString(),
		description: "Leen - weekly salary",
		amount: 10,
		isPaid: false,
	},
	{
		id: 22,
		date: new Date("8/16/2025").toLocaleDateString(),
		description: "Leen - School outfit",
		amount: 24,
		isPaid: false,
	},
	{
		id: 23,
		date: new Date("8/16/2025").toLocaleDateString(),
		description: "Leen - Book - novel",
		amount: 20,
		isPaid: false,
	},
	{
		id: 24,
		date: new Date("8/17/2025").toLocaleDateString(),
		description: "Dina - Makeup - Original Brands",
		amount: 40,
		isPaid: false,
	},
	{
		id: 25,
		date: new Date("8/17/2025").toLocaleDateString(),
		description: "Leen - School stationary",
		amount: 11,
		isPaid: false,
	},
	{
		id: 26,
		date: new Date("8/7/2025").toLocaleDateString(),
		description: "Dina - Birthday shipping fees - Aramex",
		amount: 35,
		isPaid: false,
	},
];
export default expenses;

// let expenses = [
// 	{
// 		id: 1,
// 		date: new Date("7/25/2025").toLocaleDateString(),
// 		description: "Dinner - Shawerma 3al Saj",
// 		amount: 5.5,
// 		isPaid: false,
// 	},
// 	{
// 		id: 2,
// 		date: new Date("7/31/2025").toLocaleDateString(),
// 		description: "Car refuel",
// 		amount: 20,
// 		isPaid: false,
// 	},
// 	{
// 		id: 3,
// 		date: new Date("8/2/2025").toLocaleDateString(),
// 		description: "Monthly rental",
// 		amount: 150,
// 		isPaid: false,
// 	},
// 	{
// 		id: 4,
// 		date: new Date("8/5/2025").toLocaleDateString(),
// 		description: "Shopping - new sneakers",
// 		amount: 35,
// 		isPaid: false,
// 	},
// 	{
// 		id: 5,
// 		date: new Date("8/4/2025").toLocaleDateString(),
// 		description: "House monthly bills",
// 		amount: 75.5,
// 		isPaid: false,
// 	},
// 	{
// 		id: 6,
// 		date: new Date("8/3/2025").toLocaleDateString(),
// 		description: "Home maintenance: Washing Machine",
// 		amount: 15,
// 		isPaid: false,
// 	},
// ];
// export default expenses;
