let expenses = [
	{
		id: 1,
		date: new Date("7/30/2025").toLocaleDateString(),
		description: "Leen's Hair Dresser",
		amount: 10,
		isPaid: false,
	},
	{
		id: 2,
		date: new Date("7/31/2025").toLocaleDateString(),
		description: "Leen's weekly salary",
		amount: 10,
		isPaid: false,
	},
	{
		id: 3,
		date: new Date("8/2/2025").toLocaleDateString(),
		description: "Dina's day out with Judy",
		amount: 20,
		isPaid: false,
	},
	{
		id: 4,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Dina's monthly expenses salary",
		amount: 70,
		isPaid: false,
	},
	{
		id: 5,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen 9th grade - tuitions",
		amount: 2112.5,
		isPaid: false,
	},
	{
		id: 6,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen 9th grade - Books",
		amount: 365,
		isPaid: false,
	},
	{
		id: 7,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Dina 2nd year 1st semester tuitions + bus",
		amount: 1666,
		isPaid: false,
	},
	{
		id: 8,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Home maintenance: Washing Machine",
		amount: 15,
		isPaid: false,
	},
	{
		id: 9,
		date: new Date("8/6/2025").toLocaleDateString(),
		description: "Amazon - Dina's birthday gifts",
		amount: 54,
		isPaid: false,
	},
	{
		id: 10,
		date: new Date("8/4/2025").toLocaleDateString(),
		description: "Leen's - phone monthly recharge",
		amount: 15,
		isPaid: false,
	},
	{
		id: 11,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Leen & Haya Dinner - Better Burger",
		amount: 10.55,
		isPaid: false,
	},
	{
		id: 12,
		date: new Date("8/5/2025").toLocaleDateString(),
		description: "Click transfer - Dina's monthly salary",
		amount: 70,
		isPaid: false,
	},
	{
		id: 13,
		date: new Date("8/6/2025").toLocaleDateString(),
		description: "Udemy- 2 projects Core - React",
		amount: 15,
		isPaid: false,
	},
	{
		id: 14,
		date: new Date("7/20/2025").toLocaleDateString(),
		description: "Leen's MUN",
		amount: 55,
		isPaid: false,
	},
	{
		id: 15,
		date: new Date("8/7/2025").toLocaleDateString(),
		description: "Fish tank supplies",
		amount: 9,
		isPaid: false,
	},
	{
		id: 16,
		date: new Date("7/15/2025").toLocaleDateString(),
		description: "Shein",
		amount: 51,
		isPaid: false,
	},
	{
		id: 17,
		date: new Date("7/27/2025").toLocaleDateString(),
		description: "Leen's shopping - Bra + shoes",
		amount: 60,
		isPaid: false,
	},
	{
		id: 18,
		date: new Date("8/7/2025").toLocaleDateString(),
		description: "GMC fuel - 60",
		amount: 60,
		isPaid: false,
	},
];
export default expenses;

// let expenses = [
// 	{
// 		id: 1,
// 		date: new Date("7/25/2025").toLocaleDateString(),
// 		description: "Dinner - Shawerma 3al Saj",
// 		amount: 5.5,
// 		isPaid: false,
// 	},
// 	{
// 		id: 2,
// 		date: new Date("7/31/2025").toLocaleDateString(),
// 		description: "Car refuel",
// 		amount: 20,
// 		isPaid: false,
// 	},
// 	{
// 		id: 3,
// 		date: new Date("8/2/2025").toLocaleDateString(),
// 		description: "Monthly rental",
// 		amount: 150,
// 		isPaid: false,
// 	},
// 	{
// 		id: 4,
// 		date: new Date("8/5/2025").toLocaleDateString(),
// 		description: "Shopping - new sneakers",
// 		amount: 35,
// 		isPaid: false,
// 	},
// 	{
// 		id: 5,
// 		date: new Date("8/4/2025").toLocaleDateString(),
// 		description: "House monthly bills",
// 		amount: 75.5,
// 		isPaid: false,
// 	},
// 	{
// 		id: 6,
// 		date: new Date("8/3/2025").toLocaleDateString(),
// 		description: "Home maintenance: Washing Machine",
// 		amount: 15,
// 		isPaid: false,
// 	},
// ];
// export default expenses;
